[build]
  command = "gatsby build"
  publish = "public"

[build.environment]
  NODE_VERSION = "18.17.0"
  NODE_ENV = "production"
  NPM_FLAGS = "--legacy-peer-deps"

[build.processing]
  skip_processing = true

[[plugins]]
  package = "@netlify/plugin-gatsby"

[context.production.environment]
  NODE_ENV = "production"
