[build]
  command = "gatsby build"
  publish = "public"

[build.environment]
  NODE_VERSION = "20.18.0"
  NODE_ENV = "development"
  NPM_VERSION = "10.8.2"
  NPM_FLAGS = "--legacy-peer-deps --loglevel verbose"
  NPM_CONFIG_IGNORE_OPTIONAL = "true"

[[plugins]]
  package = "@netlify/plugin-gatsby"

[context.production.environment]
  NODE_ENV = "production"
  NPM_VERSION = "9.1.3"
  NPM_CONFIG_IGNORE_OPTIONAL = "true"
