[build]
  command = "gatsby build"
  publish = "public"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.1.3"
  NPM_FLAGS = "--legacy-peer-deps --loglevel verbose"
  NPM_CONFIG_IGNORE_OPTIONAL = "true"
  GATSBY_CONCURRENT_DOWNLOAD = "20"
  GATSBY_CPU_COUNT = "2"

[[plugins]]
  package = "@netlify/plugin-gatsby"

[context.production.environment]
  NODE_ENV = "production"
  WPGRAPHQL_URL = "https://underfloripa.com.br/graphql"
